blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('myblog.urls',namespace='blog')),
    url(r'', include('comments.urls',namespace='comments')),
]

comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
	url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from myblog import views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$|^index.html', views.HomepageView.as_view(),name='home'),
    url(r'^about.html', TemplateView.as_view(template_name='about.html'), name='aboutme'),
    url(r'^contact.html', TemplateView.as_view(template_name='contact.html'), name='contact'),
    #url(r'^post/(?P<post_id>[0-9]+)/$', views.postdetail, name='detail'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<id>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
	url(r'^mdeditor/', include('mdeditor.urls'), name='category'),
	url(r'^editor/', views.editor),
]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.db import models

class Comment(models.Model):
	name = models.CharField(max_length=50)
	email = models.EmailField(max_length=50)
	url = models.URLField(blank=True)
	text = models.TextField()
	created_time = models.DateTimeField(auto_now_add=True)
	
	post = models.ForeignKey('myblog.Article')
	
	def __str__(self):
		return self.text[:20]

myblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from mdeditor.fields import MDTextField

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=20)
	
	def __str__(self):
		return self.name
	
class Tag(models.Model):
	name = models.CharField(max_length=20)
	
	def __str__(self):
		return self.name

class Article(models.Model):
	title = models.CharField(max_length=50)
	intro = models.CharField(max_length=100, blank=True)
	#body = models.TextField()
	body = MDTextField()
	created_time = models.DateTimeField()
	modified_time = models.DateTimeField()
	numsay = models.IntegerField(default=0)
	numread = models.IntegerField(default=0)
	
	category = models.ForeignKey(Category)
	tags = models.ManyToManyField(Tag, blank=True)
	
	author = models.ForeignKey(User)
	
	def __str__(self):
		return self.title
		
	def get_absolute_url(self):
		return reverse('blog:detail', kwargs={'post_id':self.id})
	
	def increase_numread(self):
		self.numread+=1
		self.save(update_fields=['numread'])
	
	class Meta:
		ordering = ['-created_time']
class ExampleModel(models.Model):
	name = models.CharField(max_length=10)
	content = MDTextField()

myblog/forms.py
from django import forms
from .models import ExampleModel

class MDEditorModleForm(forms.ModelForm):

    class Meta:
        model = ExampleModel
        fields = '__all__'

myblog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from myblog.models import Article, Category
import markdown
from comments.forms import CommentForm
from .forms import MDEditorModleForm
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify

def editor(request):
	form = MDEditorModleForm
	return render(request, 'editor.html', {'form':form})

class HomepageView(ListView):
	model = Article
	template_name = 'index.html'
	context_object_name = 'articles'
	paginate_by = 5

	def get_context_data(self, **kwargs):
		"""
		在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
		例如 render(request, 'blog/index.html', context={'post_list': post_list})，
		这里传递了一个 {'post_list': post_list} 字典给模板。
		在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
		所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
		"""

		# 首先获得父类生成的传递给模板的字典。
		context = super().get_context_data(**kwargs)

		# 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
		# paginator 是 Paginator 的一个实例，
		# page_obj 是 Page 的一个实例，
		# is_paginated 是一个布尔变量，用于指示是否已分页。
		# 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
		# 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
		# 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
		paginator = context.get('paginator')
		page = context.get('page_obj')
		is_paginated = context.get('is_paginated')

		# 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
		pagination_data = self.pagination_data(paginator, page, is_paginated)

		# 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
		context.update(pagination_data)

		# 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
		# 注意此时 context 字典中已有了显示分页导航条所需的数据。
		return context

	def pagination_data(self, paginator, page, is_paginated):
		if not is_paginated:
			# 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
			return {}

		# 当前页左边连续的页码号，初始值为空
		left = []

		# 当前页右边连续的页码号，初始值为空
		right = []

		# 标示第 1 页页码后是否需要显示省略号
		left_has_more = False

		# 标示最后一页页码前是否需要显示省略号
		right_has_more = False

		# 标示是否需要显示第 1 页的页码号。
		# 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
		# 其它情况下第一页的页码是始终需要显示的。
		# 初始值为 False
		first = False

		# 标示是否需要显示最后一页的页码号。
		# 需要此指示变量的理由和上面相同。
		last = False

		# 获得用户当前请求的页码号
		page_number = page.number

		# 获得分页后的总页数
		total_pages = paginator.num_pages

		# 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
		page_range = paginator.page_range

		if page_number == 1:
			# 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
			# 此时只要获取当前页右边的连续页码号，
			# 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
			# 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
			right = page_range[page_number:page_number + 2]

			# 如果最右边的页码号比最后一页的页码号减去 1 还要小，
			# 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
			if right[-1] < total_pages - 1:
				right_has_more = True

			# 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
			# 所以需要显示最后一页的页码号，通过 last 来指示
			if right[-1] < total_pages:
				last = True

		elif page_number == total_pages:
			# 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
			# 此时只要获取当前页左边的连续页码号。
			# 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
			# 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

			# 如果最左边的页码号比第 2 页页码号还大，
			# 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
			if left[0] > 2:
				left_has_more = True

			# 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
			# 所以需要显示第一页的页码号，通过 first 来指示
			if left[0] > 1:
				first = True
		else:
			# 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
			# 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
			right = page_range[page_number:page_number + 2]

			# 是否需要显示最后一页和最后一页前的省略号
			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True

			# 是否需要显示第 1 页和第 1 页后的省略号
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True

		data = {
			'left': left,
			'right': right,
			'left_has_more': left_has_more,
			'right_has_more': right_has_more,
			'first': first,
			'last': last,
		}

		return data

class CategoryView(HomepageView):
	def get_queryset(self):
		cate = get_object_or_404(Category, id=self.kwargs.get('id'))
		return super(CategoryView, self).get_queryset().filter(category=cate)

class ArchivesView(HomepageView):
	def get_queryset(self):
		return super(ArchivesView, self).get_queryset().filter(created_time__year=self.kwargs.get('year'), created_time__month=self.kwargs.get('month'))

def postdetail(request,post_id):
	article = get_object_or_404(Article,id = post_id)
	article.increase_numread()
	article.body = markdown.markdown(article.body,extensions = ['markdown.extensions.extra','markdown.extensions.codehilite','markdown.extensions.toc'])
	form = CommentForm()
	comment_list = article.comment_set.all()
	context = {'article': article,
				'form': form,
				'comment_list': comment_list
	}
	return render(request, 'single.html', context=context)
def postdetail_(request,post_id):
	article = get_object_or_404(Article,id = post_id)
	article.body = markdown.markdown(article.body,extensions=['markdown.extensions.codehilite','markdown.extensions.extra','markdown.extensions.toc'])#,extension = ['markdown.extensions.extra','markdown.extensions.codehilite','markdown.extensions.toc']

	return render(request, 'text.html', {'article':article})

class PostDetailView(DetailView):
	model = Article
	template_name = 'single.html'
	context_object_name = 'article'

	def get(self, request, *args, **kwargs):
		response = super(PostDetailView, self).get(request, *args, **kwargs)
		self.object.increase_numread()
		return response

	def get_object(self, queryset=None):
		post = super(PostDetailView, self).get_object(queryset=None)
		md = markdown.Markdown(extensions=[
			'markdown.extensions.extra',
			'markdown.extensions.codehilite',
			TocExtension(slugify=slugify),
		])
		post.body = md.convert(post.body)
		post.toc = md.toc
		return post

	def get_context_data(self, **kwargs):
		context = super(PostDetailView, self).get_context_data(**kwargs)
		form = CommentForm()
		comment_list = self.object.comment_set.all()
		context.update({
			'form': form,
			'comment_list': comment_list
		})
		return context

myblog/templates/about.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- css -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}" >
		<link rel="stylesheet" href="{% static 'css/pace.css' %}">
		<link rel="stylesheet" href="{% static 'css/custom.css' %}">

		<!-- js -->
		<script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/pace.min.js' %}"></script>
		<script src="{% static 'js/modernizr.custom.js' %}"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
									<li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
									<li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
									<li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
									<li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="{% static 'img/me.jpg' %}" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

myblog/templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">
	
    <!-- js -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
	
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{%url 'blog:home'%}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{%url 'blog:home'%}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{%url 'blog:aboutme'%}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{%url 'blog:contact'%}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
				{%block main%}
				{%endblock main%}
            </main>
            <aside class="col-md-4">
                {%block toc%}
				{%endblock toc%}
				<div class="widget widget-recent-posts">
					<h3 class="widget-title">最新文章</h3>
					{% get_recent_posts as recent_post_list%}
					<ul>
						{% for post in recent_post_list %}
						<li>
							<a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a>
						</li>
						{% endfor %}
					</ul>
				</div>
				<div class="widget widget-archives">
					<h3 class="widget-title">归档</h3>
					{% archives as date_list %}
					<ul>
						{% for date_ in date_list%}
						<li>
							<a href="{%url 'blog:archives' date_.year date_.month%}">{{date_.year}}年 {{date_.month}} 月</a>
						</li>
						{%endfor%}
					</ul>
				</div>

				<div class="widget widget-category">
					<h3 class="widget-title">分类</h3>
					{% get_categories as category_list %}
					<ul>
						{%for category in category_list%}
						<li>
							<a href="{%url 'blog:category' category.id%}">{{category.name}}<span class="post-count"></span></a>
						</li>
						{%endfor%}
					</ul>
				</div>

				<div class="widget widget-tag-cloud">
					<h3 class="widget-title">标签云</h3>
					<ul>
						<li>
							<a href="#">Django</a>
						</li>
						<li>
							<a href="#">Python</a>
						</li>
						<li>
							<a href="#">Java</a>
						</li>
						<li>
							<a href="#">笔记</a>
						</li>
						<li>
							<a href="#">文档</a>
						</li>
						<li>
							<a href="#">AngularJS</a>
						</li>
						<li>
							<a href="#">CSS</a>
						</li>
						<li>
							<a href="#">JavaScript</a>
						</li>
						<li>
							<a href="#">Snippet</a>
						</li>
						<li>
							<a href="#">jQuery</a>
						</li>
					</ul>
				</div>
				<div class="rss">
					<a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
				</div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 By Meredith Ma
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

myblog/templates/editor.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    </head>
    <body>
        <form method="post" action="./">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <p><input type="submit" value="post"></p>
        </form>
    </body>
</html>

myblog/templates/index.html
{%extends 'base.html'%}
{% load staticfiles %}
{% load blog_tags %}

{%block main%}
	{% for article in articles %}		
	<article class="post post-1">
		<header class="entry-header">
			<h1 class="entry-title">
				<a href="{%url 'blog:detail' article.id %}">{{ article.title }}</a>
			</h1>
			<div class="entry-meta">
				<span class="post-category"><a href="#">{{ article.category }}</a></span>
				<span class="post-date"><a href="#"><time class="entry-date"
														  datetime="2012-11-09T23:15:57+00:00">{{ article.create_time }}</time></a></span>
				<span class="post-author"><a href="#">{{ article.author }}</a></span>
				<span class="comments-link"><a href="#">{{ article.numsay }} 评论</a></span>
				<span class="views-count"><a href="#">{{ article.numread }} 阅读</a></span>
			</div>
		</header>
		<div class="entry-content clearfix">
			<p>{{ article.intro }}</p>
			<div class="read-more cl-effect-14">
				<a href="{%url 'blog:detail' article.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
			</div>
		</div>
	</article>
	{% endfor %}


	{% if is_paginated %}
	<div class="pagination">
	{% if first %}
		<a href="?page=1">1</a>
	{% endif %}
	{% if left %}
		{% if left_has_more %}
			<span>...</span>
		{% endif %}
		{% for i in left %}
			<a href="?page={{ i }}">{{ i }}</a>
		{% endfor %}
	{% endif %}
	<a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
	{% if right %}
		{% for i in right %}
			<a href="?page={{ i }}">{{ i }}</a>
		{% endfor %}
		{% if right_has_more %}
			<span>...</span>
		{% endif %}
	{% endif %}
	{% if last %}
		<a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
	{% endif %}
	</div>
	{% endif %}

	<!--
	{% if is_paginated %}
	<div class="pagination-simple">
		{% if page_obj.has_previous %}
			<a href="?page={{ page_obj.previous_page_number	 }}">上一页</a>
		{% endif %}
		<span class="current">第 {{page_obj.number}} 页 / 共 {{paginator.num_pages}} 页</span>
		{% if page_obj.has_next %}
			<a href="?page={{page_obj.next_page_number }}">下一页</a>
		{% endif %}
	</div>
	{% endif %}

	<div class="pagination">
		<ul>
			<li><a href="">1</a></li>
			<li><a href="">...</a></li>
			<li><a href="">4</a></li>
			<li><a href="">5</a></li>
			<li class="current"><a href="">6</a></li>
			<li><a href="">7</a></li>
			<li><a href="">8</a></li>
			<li><a href="">...</a></li>
			<li><a href="">11</a></li>
		</ul>
	</div>
	-->
{%endblock main%}

{%block toc%}
{% endblock toc %}

myblog/templates/single.html
{%extends 'base.html'%}
{% load staticfiles %}
{% load blog_tags %}
{%block main%}
	<article class="post post-1">
		<header class="entry-header">
			<h1 class="entry-title">{{article.title}}</h1>
			<div class="entry-meta">
				<span class="post-category"><a href="#">{{article.category}}</a></span>
				<span class="post-date"><a href="#"><time class="entry-date"
														  datetime="2012-11-09T23:15:57+00:00">{{article.created_time}}</time></a></span>
				<span class="post-author"><a href="#">{{article.author}}</a></span>
				<span class="comments-link"><a href="#">{{article.numsay}} 评论</a></span>
				<span class="views-count"><a href="#">{{article.numread}} 阅读</a></span>
			</div>
		</header>
		<div class="entry-content clearfix" >
			{{article.body|safe}}
		</div>
	</article>
	<section class="comment-area" id="comment-area">
		<hr>
		<h3>发表评论</h3>
		<form action="{%url 'comments:post_comment' article.id%}" method="post" class="comment-form">
			{% csrf_token %}
			<div class="row">
				<div class="col-md-4">
					<label for="{{form.name.id_for_label}}">名字：</label>
					{{form.name}}
					{{form.name.errors}}
					<!--<input type="text" id="name" name="name" required>-->
				</div>
				<div class="col-md-4">
					<label for="{{form.email.id_for_label}}">邮箱：</label>
					{{form.email}}
					{{form.email.errors}}
					<!--<input type="email" id="id_email" name="email" required>-->
				</div>
				<div class="col-md-4">
					<label for="{{form.url.id_for_label}}">网址：</label>
					{{form.url}}
					{{form.url.errors}}
					<!--<input type="text" id="id_url" name="url">-->
				</div>
				<div class="col-md-12">
					<label for="{{form.text.id_for_label}}">评论：</label>
					{{form.text}}
					{{form.text.errors}}
					<!--<textarea name="text" id="id_comment" required></textarea>-->
					<button type="submit" class="comment-btn">发表</button>
				</div>
			</div>    <!-- row -->
		</form>
		<div class="comment-list-panel">
			<!--<h3>评论列表，共 <span>4</span> 条评论</h3>-->
			<ul class="comment-list list-unstyled">
				{%for comment in comment_list%}
				<li class="comment-item">
					<span class="nickname">{{comment.name}}</span>
					<time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{comment.created_time}}</time>
					<div class="text">
						{{comment.text}}
					</div>
				</li>
				{%endfor%}
			</ul>
		</div>
	</section>
{%endblock main%}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ article.toc|safe }}
    </div>
{% endblock toc %}

myblog/templates/text.html
{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">

{{article.body|safe}}